In [ ]:
from transformers import pipeline
# senti=pipeline('sentiment-analysis')
ner = pipeline("ner", grouped_entities=True)

In [1]:
sequence = "Hugging Face Inc. is a company based in New York City. Its headquarters are in DUMBO, therefore very close to the Manhattan Bridge which is visible from the window."
output = ner(sequence)
print(output)

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing TFBertForTokenClassification: ['dropout_147']
- This IS expected if you are initializing TFBertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing TFBertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of TFBertForTokenClassification were not initialized from the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english and are newly initialized: ['dropout_73']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


[{'entity_group': 'I-ORG', 'score': 0.9970663785934448, 'word': 'Hugging Face Inc'}, {'entity_group': 'I-LOC', 'score': 0.9993778268496195, 'word': 'New York City'}, {'entity_group': 'I-LOC', 'score': 0.9571147362391154, 'word': 'DUMBO'}, {'entity_group': 'I-LOC', 'score': 0.983814150094986, 'word': 'Manhattan Bridge'}]


In [2]:
sequence = """Spotcap was founded with an in depth understanding of financial services, 
an entrepreneurial spirit and a clear objective: to deliver simple and swift loans to 
businesses so that they can focus on what matters to them."""

ner(sequence)

In [27]:
senti(sequence)

[{'label': 'POSITIVE', 'score': 0.9993500709533691}]

In [5]:
batch_string=['VISA DEBIT PURCHASE CARD 8061 GOOGLE*ADWS8409660624 SINGAPORE',
    'VISA DEBIT PURCHASE CARD 8061 RENTALCARTOLLPH131865 PARRAMATTA',
    'Gutschrift Onlinebanking ner 2014 BG/000000217 OPSKATWW AT916000050110110437 Piratenpartei Österreichs Mitgliedsbeiträge LO-Anteil Jänner 2014',
    'SWITCH Energievertriebsgesellschaft Bel. 613661801 EUR 3700 OG/000001242'
 ,'SIX Payment Services (Europe) S.A.'
,'Stadt Wien Buchhaltungsabteilung 33 POS 6507 280 K001 26.08. 16:45 JET-TANKSTELLEMUENCHEN80687'
,'Entgelt für Buchungsposten und Belege'
,'Entgelt für Manipulation'
,'Entgelt für Buchungsposten und Belege'
    ]

In [6]:
s=batch_string[4]
s=' '.join(x for x in s.split() if x)
print(s)
ner(s)

SIX Payment Services (Europe) S.A.


[{'entity_group': 'I-ORG',
  'score': 0.9951438426971435,
  'word': 'SIX Payment Services'},
 {'entity_group': 'I-LOC', 'score': 0.9991500973701477, 'word': 'Europe'},
 {'entity_group': 'I-ORG', 'score': 0.9862900376319885, 'word': 'S'},
 {'entity_group': 'I-ORG', 'score': 0.8623150587081909, 'word': 'A'}]

In [7]:
ner(batch_string)

[[],
 [{'entity_group': 'I-ORG', 'score': 0.689075231552124, 'word': 'VI'},
  {'entity_group': 'I-ORG', 'score': 0.7900227010250092, 'word': 'REN'},
  {'entity_group': 'I-ORG', 'score': 0.8560181558132172, 'word': '##LCAR'},
  {'entity_group': 'I-ORG',
   'score': 0.9562845925490061,
   'word': 'PARRAMATTA'}],
 [{'entity_group': 'I-ORG',
   'score': 0.8847724114145551,
   'word': 'Gutschrift Onlinebanking'},
  {'entity_group': 'I-ORG', 'score': 0.9304457902908325, 'word': 'OPSKAT'},
  {'entity_group': 'I-ORG',
   'score': 0.8471984639763832,
   'word': 'Piratenpartei Österre'},
  {'entity_group': 'I-MISC', 'score': 0.4645432233810425, 'word': '##ich'},
  {'entity_group': 'I-ORG', 'score': 0.8051902651786804, 'word': 'Mi'},
  {'entity_group': 'I-ORG', 'score': 0.7866743206977844, 'word': '##ge'},
  {'entity_group': 'I-ORG', 'score': 0.6178044676780701, 'word': 'An'},
  {'entity_group': 'I-ORG', 'score': 0.8137967586517334, 'word': '##il J'},
  {'entity_group': 'I-MISC', 'score': 0.66608

In [9]:
from transformers import TFAutoModelForTokenClassification, AutoTokenizer
import tensorflow as tf
model = TFAutoModelForTokenClassification.from_pretrained("dbmdz/bert-large-cased-finetuned-conll03-english")
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
label_list = [
    "O",       # Outside of a named entity
    "B-MISC",  # Beginning of a miscellaneous entity right after another miscellaneous entity
    "I-MISC",  # Miscellaneous entity
    "B-PER",   # Beginning of a person's name right after another person's name
    "I-PER",   # Person's name
    "B-ORG",   # Beginning of an organisation right after another organisation
    "I-ORG",   # Organisation
    "B-LOC",   # Beginning of a location right after another location
    "I-LOC"    # Location
]
sequence = """Spotcap was founded with an in-depth understanding of financial services, an entrepreneurial spirit and a clear objective: to deliver simple and swift loans to businesses so that they can focus on what matters to them."""
# Bit of a hack to get the tokens with the special tokens
tokens = tokenizer.tokenize(tokenizer.decode(tokenizer.encode(sequence)))
inputs = tokenizer.encode(sequence, return_tensors="tf")
outputs = model(inputs)[0]
predictions = tf.argmax(outputs, axis=2)
predictions

All model checkpoint weights were used when initializing TFBertForTokenClassification.

All the weights of TFBertForTokenClassification were initialized from the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForTokenClassification for predictions without further training.


<tf.Tensor: shape=(1, 44), dtype=int64, numpy=
array([[0, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [10]:
outputs

<tf.Tensor: shape=(1, 44, 9), dtype=float32, numpy=
array([[[ 1.05342808e+01, -1.98900318e+00, -1.52899575e+00,
         -1.87146163e+00, -1.85586977e+00, -1.65091538e+00,
         -1.16169572e+00, -1.65713489e+00,  2.06491515e-01],
        [ 1.70016956e+00, -2.23279977e+00,  5.36611974e-01,
         -3.22892427e+00,  7.17216015e-01, -1.32830763e+00,
          5.50244617e+00, -3.15014744e+00, -9.81135011e-01],
        [ 1.40911281e+00, -2.61523175e+00, -1.16079710e-01,
         -3.03250360e+00,  9.33667064e-01, -1.49741876e+00,
          5.81488848e+00, -2.85015631e+00, -6.01672053e-01],
        [ 1.10054064e+01, -2.33733296e+00, -1.20209897e+00,
         -2.65940404e+00, -9.94906843e-01, -1.71097553e+00,
          8.37378442e-01, -2.11152172e+00, -7.69982517e-01],
        [ 1.14504471e+01, -2.13699508e+00, -8.48211825e-01,
         -2.72059083e+00, -9.43282366e-01, -2.10378718e+00,
          1.91422477e-01, -2.14462543e+00, -5.64634621e-01],
        [ 1.12415752e+01, -2.30828881e+00, 

In [ ]:
tokenizer.decode(outputs)